config/routes.rb
Rails.application.routes.draw do
  get 'reviews/_form'

  get 'reviews/edit'

  get 'reviews/show'

  get 'reviews/index'

  get 'reviews/new'

  get 'actors/_form'

  get 'actors/edit'

  get 'actors/show'

  get 'actors/index'

  get 'actors/new'

  devise_for :users
  resource :profile, except: [:destroy]
  resources :movies

   root 'welcome#index'

end

app/models/actor.rb
class Actor < ActiveRecord::Base
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :movie
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def _form
  end

  def edit
  end

  def show
  end

  def index
  end

  def new
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
  profile_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  def index
    @movies = Movie.order(title: :asc)
  end

  def show
      @movie = Movie.find(params[:id])
  end

   def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to @movie
    else
      render :new
    end
  end

   def edit
    
  end

  def update
    if @movie.update_attributes(movie_params)
      redirect_to @movie
    else
      render :edit
    end

  end

  def destroy
    @movie.destroy
    redirect_to movies_path
  end

  private

  def set_movie
    @movie = Movie.find(params[:id])
  end

  def movie_params
    params.require(:movie).permit(:title, :summary, :youtube, :thumbnail)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
 before_action :authenticate_user!
 before_action :set_profile, only: [:show, :edit, :update]
 before_action :check_existing_profile, only: [:new, :create]

 def show
 end

 def new
   @profile = current_user.build_profile
 end

 def create
   @profile = current_user.build_profile(profile_params)
   if @profile.save
     redirect_to profile_path
   else
     render :new
   end
 end

 def edit
 end

 def update
   if @profile.update_attributes(profile_params)
     redirect_to profile_path
   else
     render :edit
   end
 end

private

 def set_profile
   @profile = current_user.profile
     if !@profile
     redirect_to new_profile_path and return
   end
 end

 def profile_params
   params.require(:profile).permit(:name)
 end

 def check_existing_profile
   if current_user.profile
     redirect_to profile_path and return
   end
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def _form
  end

  def edit
  end

  def show
  end

  def index
  end

  def new
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end
end

app/helpers/actors_helper.rb
module ActorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/actors/_form.html.erb
<h1>Actors#_form</h1>
<p>Find me in app/views/actors/_form.html.erb</p>

app/views/actors/edit.html.erb
<h1>Actors#edit</h1>
<p>Find me in app/views/actors/edit.html.erb</p>

app/views/actors/index.html.erb
<h1>Actors#index</h1>
<p>Find me in app/views/actors/index.html.erb</p>

app/views/actors/new.html.erb
<h1>Actors#new</h1>
<p>Find me in app/views/actors/new.html.erb</p>

app/views/actors/show.html.erb
<h1>Actors#show</h1>
<p>Find me in app/views/actors/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vhsdb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/movies/_form.html.erb
<%= form_for @movie do |f| %>
<p>  <%= f.label :title %>
    <%= f.text_field :title %>
</p>
<p>  <%= f.label :summary %>
    <%= f.text_field :summary %>
</p>
<p>  <%= f.label :youtube %>
    <%= f.text_field :youtube %>
</p>
<p>  <%= f.label :thumbnail %>
    <%= f.text_field :thumbnail%>
</p>


<%= f.submit %> or <%= link_to 'Cancel', movies_path %>

<% end %>

app/views/movies/edit.html.erb
<h1>Movies Edit Page</h1>

<%= render 'form' %>

app/views/movies/index.html.erb
<h1><%= params[:action] == 'index' ? 'Movies' : params[:action].titleize %></h1>

<%= link_to 'Create Movie', new_movie_path %>
<h1>Movies Index</h1>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>YouTube</th>
      <th>Thumbnail</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>

    <% @movies.each do |movie| %>
    <tr>
      <td><%= link_to movie.title.titleize, movie %></td>
      <td><%= movie.summary %></td>
      <td><%= movie.youtube %></td>
      <td><%= movie.thumbnail %></td>
      <td>
        <%= link_to 'Edit', edit_movie_path(movie) %>|
        <%= link_to 'Delete', movie, method: :delete %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render partial: 'form' %>

app/views/movies/show.html.erb
<h1>Show it up</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Summary</th>
      <th>YouTube</th>
      <th>Thumbnail</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>


    <tr>
      <td><%= @movie.title %></td>
      <td><%= @movie.summary %></td>
      <td><%= @movie.youtube.html_safe %></td>
      <td><img src=<%= @movie.thumbnail %> alt=""></td>
      <td>

      </td>
    </tr>

  </tbody>
</table>

app/views/profiles/_form.html.erb
<%= form_for @profile, url: profile_path do |f| %>
<p>
  <%= f.label :name %>
  <%= f.text_field :name %>
</p>
  <%= f.submit %>
<% end %>

app/views/profiles/edit.html.erb
<h2>Update Profile</h2>


<%= render 'form' %>

app/views/profiles/new.html.erb
<h2>Create Profile</h2>

<%= render 'form' %>

app/views/profiles/show.html.erb
<p> <%= @profile.name %> </p>
<%= link_to 'Edit Profile', edit_profile_path %>


<h1>Here is my profile page.  This is where the user will go after they login??</h1>

app/views/reviews/_form.html.erb
<h1>Reviews#_form</h1>
<p>Find me in app/views/reviews/_form.html.erb</p>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/reviews/new.html.erb
<h1>Reviews#new</h1>
<p>Find me in app/views/reviews/new.html.erb</p>

app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

app/views/welcome/index.html.erb
<h1>VHS|DB</h1>



<% if current_user %>
<p>Click here to
<%= link_to 'logout', destroy_user_session_path, method: :delete %>
</p>
<%else%>
<ul>
  <li>If you have an account <%= link_to 'Login', new_user_session_path %></li>
  <li>To access the database <%= link_to 'Create New User', new_user_registration_path %></li>
</ul>

<% end %>